apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmirza-jmsbwa-deploy
  labels:
    app: skmirza-jmsbwa-deploy-lb01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skmirza-jmsbwa-app
  template:
    metadata:
      labels:
        app: skmirza-jmsbwa-app
    spec:
      containers:
      - name: skmirza-jmsbwa-container
        image: sameer014/skmirza-jmsbwa-img:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: skmirza-jmsbwa-np-service
  labels:
    app: skmirza-jmsbwa-np-app
spec:
  selector:
    app: skmirza-jmsbwa-app

  type: NodePort
  ports:
  - nodePort: 30014
    port: 8080
    targetPort: 8080
