apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmirza-jmsbwa-deploy
  labels:
    app: skmirza-jmsbwa-deploy-lb01
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: skmirza-jmsbwa-app
    spec:
      containers:
      - name: skmirza-jmsbwa-container
        image: sameer014/skmirza-jmsvwa-img:latest
        ports:
        - containerPort: 8080
    selector:
      matchLabels:
        app: skmirza-jmsbwa-app
---
apiVersion: v1
kind: Service
metadata:
  name: skmirza-jmsbwa-np-service
  labels:
    app: skmirza-jmsbwa-np-app
spec:
  selector:
    app: skmirza-jmsbwa-deploy-lb01

  type: NodePort
  ports:
  - nodePort: 30014
    port: 8080
    targetPort: 8080
